---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2
  template:
    metadata:
      labels:
        app: project2
    spec:
      containers:
        - name: project2
          image: quay.io/xinmeng_chen/project2:fc7a204
         
          ports:
            - containerPort: 5001


